# Generated by Django 5.2 on 2025-04-14 14:33

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.TextField(blank=True)),
                ('NIN', models.IntegerField(unique=True)),
                ('location', models.IntegerField(default=35)),
                ('contact', models.DateField(default=20)),
                ('amount_due', models.IntegerField(default=False)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('product_name', models.TextField(default=255)),
                ('type_of_produce', models.IntegerField(default=255)),
                ('tonnage', models.IntegerField()),
                ('Dispatch_date', models.DateField(auto_now_add=True)),
                ('is_sold_on_deferred_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True)),
                ('tonnage', models.IntegerField()),
                ('buyers_name', models.IntegerField(default=35)),
                ('date_and_time', models.DateField(auto_now_add=True)),
                ('salesagent_name', models.TextField(default=255)),
                ('is_sold_on_cash', models.BooleanField(default=False)),
                ('is_sold_on_deferred_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_produce', models.TextField(blank=True, default=255)),
                ('type_of_produce', models.IntegerField(default=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_of_produce', models.DateField(auto_now_add=True)),
                ('tonnage', models.IntegerField()),
                ('cost', models.IntegerField(default=25)),
                ('name_of_dealer', models.TextField(default=20)),
                ('branch_name', models.TextField()),
                ('contact', models.CharField(default=20)),
                ('selling_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('gender', models.TextField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
