# Generated by Django 5.2 on 2025-04-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='date_and_time_of_produce',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='is_sold_on_deferred_payment',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='is_sold_on_deferred_payment',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time_of_produce',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='credit',
            name='salesagent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='buyer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='credit',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kgl_app.stock'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgl_app.stock'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='salesagent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_of_dealer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_of_produce',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kgl_app.branch'),
        ),
        migrations.AddField(
            model_name='sales',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kgl_app.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kgl_app.branch'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='type_of_produce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kgl_app.producetype'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type_of_produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgl_app.producetype'),
        ),
    ]
