# Generated by Django 5.2 on 2025-04-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0002_branch_producetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='producetype',
            old_name='name',
            new_name='type_of_produce',
        ),
    ]
