# Generated by Django 5.2 on 2025-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0003_rename_name_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='buyers_name',
            field=models.CharField(max_length=35),
        ),
    ]
