# Generated by Django 5.2 on 2025-04-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0004_alter_sales_buyers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='Dispatch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='contact',
            field=models.DateTimeField(default=20),
        ),
        migrations.AlterField(
            model_name='credit',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_and_time_of_produce',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
