# Generated by Django 5.2 on 2025-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0006_userprofile_phonenumber_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='is_sold_on_cash',
            field=models.BooleanField(),
        ),
    ]
