# Generated by Django 5.2 on 2025-04-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0008_remove_stock_current_stock_stock_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_stock',
            field=models.IntegerField(null=True),
        ),
    ]
