# Generated by Django 5.2 on 2025-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0009_stock_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kgl_app.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issued_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tonnage',
            field=models.IntegerField(default=0),
        ),
    ]
