# Generated by Django 5.2 on 2025-04-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0011_userprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_branches',
            field=models.ManyToManyField(blank=True, related_name='managers', to='kgl_app.branch'),
        ),
    ]
