# Generated by Django 5.2 on 2025-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0012_userprofile_managed_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
