# Generated by Django 5.2 on 2025-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0013_credit_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='Dispatch_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
