# Generated by Django 5.2 on 2025-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0014_alter_credit_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='Dispatch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
